### ISSUE TITLE
Table driven testing

### ISSUE THREAD

**Issue by alirezazeynali75** [optimus-hft/go-ipmux#4]
I highly recommend to use table-driven testing in `client_test` for `TestIPMux_Client` and `TestIPMux_Clients` if you want I can make a PR for it

**Comment by miladibra10** [comment]
@alirezazeynali75 
That is interesting. Your PR will be welcome.

**Comment by alirezazeynali75** [comment]
I will do it.
Do you have any convention on `branch naming` or `commits`?
